### ISSUE TITLE
Errors in log file

### ISSUE THREAD

**Issue by mauriceatkinson** [BNNorman/dragino-1#2]
I am have some code that is using your library and is reading Atlas Scientific sensors installed on a raspberry pi every 15 minutes.

I am seeing error in the error log and have listed this below.  The error seems to result in the data packet not being transmitted to my lorawan gateway  When I view the logs on my own lorawan gateway and on the TTN console I am seeing quite of lot of missing fcnt counts and thought this error might be the cause of it.

2022-04-13 07:15:01,225 - registered - 550 - INFO - checking if already registered.
2022-04-13 07:15:01,225 - registered - 556 - INFO - devaddr [38, 11, 58, 184] len 4.
2022-04-13 07:15:01,226 - registered - 572 - INFO - Already registered
2022-04-13 07:15:01,226 - getSendSettings - 259 - DEBUG - using send settings: freq 867.9 sf 9 bw 7
2022-04-13 07:15:01,226 - configureRadio - 173 - INFO - freq=867.9 sf=9 bw=7
2022-04-13 07:15:01,229 - getFOpts - 560 - INFO - check for FOpts to attach to uplink len=0 FOpts=bytearray(b'')
2022-04-13 07:15:01,230 - getFOpts - 565 - INFO - no FOpts
2022-04-13 07:15:01,230 - saveCache - 489 - INFO - Saving MAC settings
2022-04-13 07:15:01,237 - _sendPacket - 644 - DEBUG - Sending packet raw payload = [64, 184, 58, 11, 38, 0, 191, 7, 1, 14, 248, 251, 131, 225, 101, 102, 200, 119, 19, 229, 196, 194, 233, 173, 57, 24, 100, 209, 220, 122, 177, 168, 158, 94, 128, 198, 244, 193, 26, 167, 63, 54, 125, 172, 137]
2022-04-13 07:15:01,549 - on_tx_done - 426 - INFO - switching to RX1
2022-04-13 07:15:01,550 - getRX1Settings - 278 - DEBUG - RX1 settings : freq 867.9 sf 9 bw 7
2022-04-13 07:15:01,550 - configureRadio - 173 - INFO - freq=867.9 sf=9 bw=7
2022-04-13 07:15:01,553 - on_tx_done - 432 - INFO - setting timer delay {delay} to switch to RX2
2022-04-13 07:30:06,175 - registered - 550 - INFO - checking if already registered.
2022-04-13 07:30:06,175 - registered - 556 - INFO - devaddr [38, 11, 58, 184] len 4.
2022-04-13 07:30:06,176 - registered - 572 - INFO - Already registered
2022-04-13 07:30:06,176 - _sendPacket - 664 - ERROR - list index out of range
Traceback (most recent call last):
File "/home/pi/water-quality-lorawan-dragino-pi/dragino/dragino.py", line 601, in _sendPacket
self.configureRadio(radioSettings.SEND)
File "/home/pi/water-quality-lorawan-dragino-pi/dragino/dragino.py", line 167, in configureRadio
freq,sf,bw=self.MAC.getSendSettings()
File "/home/pi/water-quality-lorawan-dragino-pi/dragino/MAChandler.py", line 254, in getSendSettings
freq=self.cache[CHANNEL_TX_FREQS][self.currentChannel]
IndexError: list index out of range
2022-04-13 07:45:10,805 - registered - 550 - INFO - checking if already registered.
2022-04-13 07:45:10,806 - registered - 556 - INFO - devaddr [38, 11, 58, 184] len 4.
2022-04-13 07:45:10,806 - registered - 572 - INFO - Already registered
2022-04-13 07:45:10,806 - getSendSettings - 259 - DEBUG - using send settings: freq 867.3 sf 9 bw 7
2022-04-13 07:45:10,807 - configureRadio - 173 - INFO - freq=867.3 sf=9 bw=7
2022-04-13 07:45:10,810 - getFOpts - 560 - INFO - check for FOpts to attach to uplink len=0 FOpts=bytearray(b'')
2022-04-13 07:45:10,810 - getFOpts - 565 - INFO - no FOpts
2022-04-13 07:45:10,811 - saveCache - 489 - INFO - Saving MAC settings
2022-04-13 07:45:10,818 - _sendPacket - 644 - DEBUG - Sending packet raw payload = [64, 184, 58, 11, 38, 0, 192, 7, 1, 69, 38, 121, 70, 183, 134, 70, 218, 89, 24, 112, 138, 157, 254, 67, 18, 49, 180, 165, 190, 181, 131, 171, 181, 38, 9, 173, 213, 19, 241, 221, 77, 6, 20, 150, 25]
2022-04-13 07:45:11,131 - on_tx_done - 426 - INFO - switching to RX1
2022-04-13 07:45:11,131 - getRX1Settings - 278 - DEBUG - RX1 settings : freq 867.3 sf 9 bw 7
2022-04-13 07:45:11,131 - configureRadio - 173 - INFO - freq=867.3 sf=9 bw=7
2022-04-13 07:45:11,135 - on_tx_done - 432 - INFO - setting timer delay {delay} to switch to RX2

**Comment by BNNorman** [comment]
Ok, I've found the problem. MAChandler.py was trying to select a TX frequency beyond the end of the TX frequency list. No other files were affected. Could you give it a try. If all is well then please close the issue.
Thanks for reporting it.

**Comment by mauriceatkinson** [comment]
@BNNorman thanks for fixing it.  I have downloaded and will test throughout the day.

**Comment by mauriceatkinson** [comment]
@BNNorman all looks great after a days transmission and no errors in the log file.  thanks for fixing.
